name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    permissions:
      id-token: 'write'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/417555860451/locations/global/workloadIdentityPools/github/providers/github'
          service_account: 'github-action-448480065@xkcd-thing.iam.gserviceaccount.com '
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: functions/package-lock.json
      - name: Install Dependencies
        run: npm ci --also=dev
        working-directory: ./functions
      - name: Deploy to Firebase
        run: |
          npm install -g firebase-tools
          firebase deploy

